global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'my_application'
    static_configs:
      - targets: ['my_application:8080']  # Replace with your application's address and port